# -*- coding: utf-8 -*-
"""firstcommittorepo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FeFJsmugKbS_iqoZopDZ1bIFb4H-a553
"""

## Got here first.

## Love Will